
Output ./../docs/vhs/direction-blank.gif
# Output ./../docs/vhs/direction-blank.mp4
# Output ./../docs/vhs/direction-blank.webm

Require echo
Require clip

Set FontSize 16
Set Width 800
Set Height 500
Set LoopOffset 0%

Sleep 200ms 
Type "clip" Sleep 200ms  
Enter Sleep 1500ms 
Down Sleep 750ms
Enter Sleep 250ms
Type "liverpool street" Enter Sleep 1250ms
Type "trafalgar square" Enter Sleep 1250ms
Sleep 3s
