
Output output/locations.gif
Output output/locations.mp4
Output output/locations.webm

Require echo
Require clip

Set FontSize 16
Set Width 1200
Set Height 600
Set LoopOffset 50%

Type "clip" Sleep 200ms  
Enter Sleep 2500ms 
Down Sleep 250ms
Down Sleep 250ms
Enter Sleep 250ms
Enter Sleep 250ms
Type "eiffel" Enter Sleep 250ms
Type "eiffel tower" Enter Sleep 2500ms
Type "Y" Sleep 250ms
Enter 
Sleep 3s
