
Output ./../docs/vhs/locations.gif
Output ./../docs/vhs/locations.mp4
# Output ./../docs/vhs/locations.webm

Require echo
Require clip

Set FontSize 16
Set Width 950
Set Height 600
Set LoopOffset 0%

# Clean Locations object
# Hide
# Type "clip location purge" Enter Sleep 200ms
# Show

# Add Big Ben
Sleep 200ms
Type "clip" Sleep 200ms
Enter Sleep 2500ms
Down Sleep 250ms
Down Sleep 250ms
Enter Sleep 250ms
Enter Sleep 250ms
Type "bigben" Enter Sleep 250ms
Type "big ben, london" Enter Sleep 2500ms
Type "Y" Sleep 250ms
Enter
Sleep 500ms
Enter
Sleep 500ms

# Add Sagrada Familia
Type "clip" Sleep 200ms
Enter Sleep 2500ms
Down Sleep 250ms
Down Sleep 250ms
Enter Sleep 250ms
Enter Sleep 250ms
Type "sagrada" Enter Sleep 250ms
Type "sagrada familia, barcelona" Enter Sleep 2500ms
Type "Y" Sleep 250ms
Enter
Sleep 500ms
Enter
Sleep 500ms

# Add Acropolis
Type "clip" Sleep 200ms
Enter Sleep 2500ms
Down Sleep 250ms
Down Sleep 250ms
Enter Sleep 250ms
Enter Sleep 250ms
Type "acropolis" Enter Sleep 250ms
Type "acropolis, athens" Enter Sleep 2500ms
Type "Y" Sleep 250ms
Enter
Sleep 500ms
Enter
Sleep 500ms

# Add Trevi Fountain
Type "clip" Sleep 200ms
Enter Sleep 2500ms
Down Sleep 250ms
Down Sleep 250ms
Enter Sleep 250ms
Enter Sleep 250ms
Type "trevi" Enter Sleep 250ms
Type "trevi fountain, rome" Enter Sleep 2500ms
Type "Y" Sleep 250ms
Enter
Sleep 500ms
Enter
Sleep 500ms

# Add Charles Bridge
Type "clip" Sleep 200ms
Enter Sleep 2500ms
Down Sleep 250ms
Down Sleep 250ms
Enter Sleep 250ms
Enter Sleep 250ms
Type "charlesbridge" Enter Sleep 250ms
Type "charles bridge, prague" Enter Sleep 2500ms
Type "Y" Sleep 250ms
Enter Sleep 500ms
Enter Sleep 1s
Enter Sleep 200ms
Type "clip location show"
Enter Sleep 5s
