name: cli-app-install
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Set to the former tested version. Should probably update this
        # to reflect the release schedule. https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Global Install
        run: npm install -g cli-path
      - name: Display clip version
        run: clip --version
