name: CLI-App - Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Set to the former tested version. Should probably update this
        # to reflect the release schedule. https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Yarn Install
        run: cd /home/runner/work/cli-path/cli-path/cli-app && yarn
      - name: Display cli-app version
        run: cd /home/runner/work/cli-path/cli-path/cli-app && yarn start --version
      - name: Display cli-app help
        run: cd /home/runner/work/cli-path/cli-path/cli-app && yarn start --help
